"""
Read in the CSV files generated by the routing script
(one for each city centre stop) and generate one file per stop
"""


from pathlib import Path
from sys import argv
from urllib.parse import quote, unquote
import pandas as pd
import json
import os

from gtfs_kit.feed import read_feed
import geopandas as gp
import pandas as pd
import ujson as json

day = argv[1]
time = argv[2]

assert day in ["wednesday", "saturday", "sunday"]
assert time in ["day", "night"]

travel_times_dir = Path(f"data/travel_times_{day}_{time}_arrival")
target_path = Path(f"data/travel_times_{day}_{time}")
target_path.mkdir(exist_ok=True)

files = list(travel_times_dir.glob("*.csv"))


def main():
    dfs = []
    for file in files:
        df = (
            pd.read_csv(file, dtype={"to_stop_id": str, "from_stop_id": str})
            .drop("Unnamed: 0", axis=1, errors="ignore")
            .drop_duplicates(subset=["from_stop_name"])
        )

        dfs.append(df)

    df_all = pd.concat(dfs)

    for from_stop_name, _df in df_all.groupby("from_stop_name"):
        stop_name_enc = quote(from_stop_name, safe="")
        _df.to_csv(target_path / f"{stop_name_enc}.csv", encoding="utf-8")


if __name__ == "__main__":
    main()
